config/routes.rb
Reclouder::Application.routes.draw do
  resources :storage_services

  devise_for :users

  root :to => 'welcome#index'

end

app/models/dropbox.rb
class DropBox < StorageService

end

app/models/s3.rb
class S3 < StorageService

end

app/models/storage_service.rb
class StorageService < ActiveRecord::Base
  TYPES = %w(s3 dropbox)
  belongs_to :user

  attr_accessible :kind, :name
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :storage_services
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :token_authenticatable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/storage_services_controller.rb
class StorageServicesController < ApplicationController
  inherit_resources

  protected

  def begin_of_association_chain
    current_user
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
    redirect_to storage_services_path if current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/storage_services_helper.rb
module StorageServicesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Reclouder" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans&subset=latin,cyrillic-ext,cyrillic,latin-ext' rel='stylesheet' type='text/css'>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="hero-unit">
          <%= yield %>
        </div>
      </div>

      <footer>
        <p style="color: white;">&copy; ReClouder 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/storage_services/_form.html.erb
<%= form_for(@storage_service, html: { class: 'form-horizontal' } ) do |f| %>
  <% if @storage_service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@storage_service.errors.count, "error") %> prohibited this storage_service from being saved:</h2>

      <ul>
      <% @storage_service.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :type, class: "control-label" %>
    <div class="controls">
      <%= f.select :type, StorageService::TYPES, include_blank: 'Choose type' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :name, class: "control-label" %>
    <div class="controls">
      <%= f.text_field :name %>
    </div>
  </div>

  <!-- dropbox fields -->
  <div class="type_specific_fields dropbox_fields">

    <div class="control-group">
      <%= f.label :dropbox_key, class: "control-label" %>
      <div class="controls">
        <%= f.text_field :dropbox_key %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :dropbox_secret, class: "control-label" %>
      <div class="controls">
        <%= f.text_field :dropbox_secret %>
      </div>
    </div>

  </div>

  <!-- s3 fields -->
  <div class="type_specific_fields s3_fields">

    <div class="control-group">
      <%= f.label :s3_access_key_id, class: "control-label" %>
      <div class="controls">
        <%= f.text_field :s3_access_key_id %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :s3_secret_access_key, class: "control-label" %>
      <div class="controls">
        <%= f.text_field :s3_secret_access_key %>
      </div>
    </div>

  </div>


  <div class="control-group">
    <div class="controls">
      <%= f.submit class: 'btn btn-large btn-primary' %>
    </div>
  </div>
<% end %>

app/views/storage_services/edit.html.erb
<h1>Editing storage_service</h1>

<%= render 'form' %>

<%= link_to 'Show', @storage_service %> |
<%= link_to 'Back', storage_services_path %>

app/views/storage_services/index.html.erb
<h2>Listing storage services</h2>

<table>
  <tr>
    <th>Kind</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @storage_services.each do |storage_service| %>
  <tr>
    <td><%= storage_service.kind %></td>
    <td><%= storage_service.name %></td>
    <td><%= link_to 'Show', storage_service %></td>
    <td><%= link_to 'Edit', edit_storage_service_path(storage_service) %></td>
    <td><%= link_to 'Destroy', storage_service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Storage service', 
      new_storage_service_path,
      class: 'btn btn-large' %>

app/views/storage_services/new.html.erb
<h1>New storage service</h1>

<%= render 'form' %>

<%= link_to 'Back', storage_services_path %>

app/views/storage_services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Kind:</b>
  <%= @storage_service.kind %>
</p>

<p>
  <b>Name:</b>
  <%= @storage_service.name %>
</p>


<%= link_to 'Edit', edit_storage_service_path(@storage_service) %> |
<%= link_to 'Back', storage_services_path %>

app/views/welcome/index.html.erb
<h1>ReClouder</h1>

<p class="lead">
  Your cloud storage tool
</p>

<%= link_to "Sign Up", 
      new_user_registration_path, 
      class: 'btn btn-large btn-primary' %>

<%= link_to "Sign In", 
      new_user_session_path, 
      class: 'btn btn-large btn-warning' %>